#!/bin/bash

# Initialize counter
count=0

# Using a while loop to display "Best School" 10 times
while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    # Increment counter
    ((count++))
done

