#!/bin/bash
# Using a while loop to display "Best School" 10 times
# Initialize counter
count=0

while [ $count -lt 10 ]; 
do
    if [ $count -eq 9 ]; 
    then
	    echo "Hi"
    fi
    echo "Best School"
    ((count++))
done

