#!/bin/bash

# Initialize counter
count=1

# Using a while loop to loop from 1 to 10
while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "Bad Luck"
    elif [ $count -eq 8 ]; then
        echo "Good Luck"
    else
        echo "Best School"
    fi
    # Increment counter
    ((count++))
done

