#!/usr/bin/env bash
# This script creates an RSA key pair named "school" with a passphrase "betty".

ssh-keygen -b 4096 -t rsa -f ~/.ssh/school -N "betty"
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in ~/.ssh/school."
echo "Your public key has been saved in ~/.ssh/school.pub."