#!/usr/bin/env bash
# This script creates an RSA key pair named "school" with a passphrase "betty".

ssh-keygen -b 4096 -t rsa -f ~/.ssh/school -N "betty"
echo "RSA key pair 'school' with passphrase 'betty' has been created."